[context.production]
  command = "npm run install && npm run build"
  REACT_APP_ENV_VAR = "supersecret"

[context.dev]
  command = "cp netlify_headers public/_headers && npm run install && npm run build"
  REACT_APP_ENV_VAR = "whateverdog"