[context.production]
  command = "npm run install && npm run build-production"
  REACT_APP_ENV_VAR = "supersecret"

[context.dev]
  command = "cp netlify_headers public/_headers && npm run install && npm run build-dev"
  REACT_APP_ENV_VAR = "whatever"