[build]
  publish = "build"

[context.production]
  command = "npm install && npm run build"
  REACT_APP_ENV_VAR = "supersecret"

[context.dev]
  command = "cp netlify_headers public/_headers && npm install && npm run build"
  REACT_APP_ENV_VAR = "whatever"